"""empty message

Revision ID: 09d19ce7e132
Revises: 2ded6fde5405
Create Date: 2016-01-11 22:22:05.932099

"""

# revision identifiers, used by Alembic.
revision = '09d19ce7e132'
down_revision = '2ded6fde5405'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articletypes', sa.Column('description', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articletypes', 'description')
    ### end Alembic commands ###
