"""empty message

Revision ID: 2ded6fde5405
Revises: None
Create Date: 2016-01-09 23:54:59.981221

"""

# revision identifiers, used by Alembic.
revision = '2ded6fde5405'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('module_id', sa.String(length=10), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articletypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('powers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['articletypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_powers',
    sa.Column('power_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['power_id'], ['powers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_powers')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('powers')
    op.drop_table('articletypes')
    op.drop_table('actions')
    ### end Alembic commands ###
