"""init

Revision ID: 550127a54af0
Revises: None
Create Date: 2016-01-08 16:55:27.053000

"""

# revision identifiers, used by Alembic.
revision = '550127a54af0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['articletypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_powers',
    sa.Column('power_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['power_id'], ['powers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_powers')
    op.drop_table('articles')
    ### end Alembic commands ###
