"""empty message

Revision ID: c8baf60a7ec2
Revises: 65cbadabfabd
Create Date: 2016-01-06 17:20:07.394000

"""

# revision identifiers, used by Alembic.
revision = 'c8baf60a7ec2'
down_revision = '65cbadabfabd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('modified_by', sa.String(length=10), nullable=True))
    op.add_column('articletypes', sa.Column('modified_by', sa.String(length=10), nullable=True))
    op.add_column('powers', sa.Column('modified_by', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('modified_by', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_by')
    op.drop_column('powers', 'modified_by')
    op.drop_column('articletypes', 'modified_by')
    op.drop_column('articles', 'modified_by')
    ### end Alembic commands ###
