"""empty message

Revision ID: e3c749d19241
Revises: 550127a54af0
Create Date: 2016-01-11 16:38:17.742000

"""

# revision identifiers, used by Alembic.
revision = 'e3c749d19241'
down_revision = '550127a54af0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articletypes', sa.Column('description', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articletypes', 'description')
    ### end Alembic commands ###
