"""empty message

Revision ID: f030316e2781
Revises: None
Create Date: 2016-01-13 13:49:33.395000

"""

# revision identifiers, used by Alembic.
revision = 'f030316e2781'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'articletypes', sa.Column('test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articletypes', 'tests', ['test_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articletypes', type_='foreignkey')
    op.drop_column(u'articletypes', 'test_id')
    op.drop_table('tests')
    ### end Alembic commands ###
